export const HOME_VIEW__START_CONNECTION = 'HOME_VIEW__START_CONNECTION'
export const HOME_VIEW__STOP_CONNECTION = 'HOME_VIEW__STOP_CONNECTION'

export const CURRENCY_LIST__REQUEST_FETCH = 'CURRENCY_LIST__REQUEST_FETCH'
export const CURRENCY_LIST__REQUEST_SUBSCRIPTION = 'CURRENCY_LIST__REQUEST_SUBSCRIPTION'
export const CURRENCY_LIST__DATA_CALLBACK = 'CURRENCY_LIST__DATA_CALLBACK'
export const CURRENCY_LIST__RESET_COMPONENT_ACTION = 'CURRENCY_LIST__RESET_COMPONENT_ACTION'

export const QUOTES_HISTORY_LIST__REQUEST_FETCH = 'QUOTES_LIST__REQUEST_FETCH'
export const QUOTES_HISTORY_LIST__REQUEST_SUBSCRIPTION = 'QUOTES_LIST__REQUEST_SUBSCRIPTION'
export const QUOTES_HISTORY_LIST__DATA_CALLBACK = 'QUOTES_LIST__DATA_CALLBACK'
export const QUOTES_HISTORY_LIST__RESET_COMPONENT_ACTION = 'QUOTES_HISTORY_LIST__RESET_COMPONENT_ACTION'

export const ORDER_FORM__GET_LIMITS = 'ORDER_FORM__GET_LIMITS'
export const ORDER_FORM__POST_ORDER = 'ORDER_FORM__POST_ORDER'

export const ORDER_HISTORY__REQUEST_FETCH = 'ORDER_HISTORY__REQUEST_FETCH'