export const HOME_VIEW__UPDATE_STATE = 'HOME_VIEW__UPDATE_STATE'
export const HOME_VIEW__SET_SELECTED_SYMBOL = 'HOME_VIEW__SET_SELECTED_SYMBOL'

export const CURRENCY_LIST__SET_DATA = 'CURRENCY_LIST__SET_DATA'
export const CURRENCY_LIST__UPDATE_DATA = 'CURRENCY_LIST__UPDATE_DATA'
export const CURRENCY_LIST__UPDATE_STATE = 'CURRENCY_LIST__UPDATE_STATE'
export const CURRENCY_LIST__RESET_COMPONENT = 'CURRENCY_LIST__RESET_COMPONENT'

export const QUOTES_HISTORY_LIST__SET_DATA = 'QUOTES_HISTORY_LIST__SET_DATA'
export const QUOTES_HISTORY_LIST__UPDATE_DATA = 'QUOTES_HISTORY_LIST__UPDATE_DATA'
export const QUOTES_HISTORY_LIST__UPDATE_STATE = 'QUOTES_HISTORY_LIST__UPDATE_STATE'
export const QUOTES_HISTORY_LIST__RESET_COMPONENT = 'QUOTES_HISTORY_LIST__RESET_COMPONENT'
export const QUOTES_HISTORY_LIST__SET_SUBSCRIPTION = 'QUOTES_HISTORY_LIST__SET_SUBSCRIPTION'

export const ORDER_FORM__SET_LIMITS = 'ORDER_FORM__SET_LIMITS'
export const ORDER_FORM__UPDATE_STATE = 'ORDER_FORM__UPDATE_STATE'
export const ORDER_FORM__RESET_COMPONENT = 'ORDER_FORM__RESET_COMPONENT'
export const ORDER_FORM__SET_RESPONSE = 'ORDER_FORM__SET_RESPONSE'

export const ORDER_HISTORY__UPDATE_STATE = 'ORDER_HISTORY__UPDATE_STATE'
export const ORDER_HISTORY__SET_DATA = 'ORDER_HISTORY__SET_DATA'
export const ORDER_HISTORY__UPDATE_DATA = 'ORDER_HISTORY__UPDATE_DATA'
export const ORDER_HISTORY__RESET_COMPONENT = 'ORDER_HISTORY__RESET_COMPONENT'