export const HOME_VIEW_STATE = {
  SOCKET_CONNECTING: 'SOCKET_CONNECTING',
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED'
}


export const CURRENCY_LIST_STATE = {
  INITIAL_FETCH: 'INITIAL_FETCH',
  REQUEST_SUBSCRIPTION: 'REQUEST_SUBSCRIPTION',
  ERROR: 'ERROR',
  DISPLAY: 'DISPLAY'
}


export const QUOTES_HISTORY_STATE = {
  INITIAL_WAIT: 'INITIAL_WAIT',
  FETCH_DATA: 'FETCH_DATA',
  EMPTY_RESPONSE: 'EMPTY_RESPONSE',
  REQUEST_SUBSCRIPTION: 'REQUEST_SUBSCRIPTION',
  ERROR: 'ERROR',
  DISPLAY: 'DISPLAY'
}


export const ORDER_FORM_STATE = {
  INITIAL_WAIT: 'INITIAL_WAIT',
  CONFIRM_ORDER: 'CONFIRM_ORDER',
  GET_LOT_SIZE: 'GET_LOT_SIZE',
  POST_REQUEST: 'POST_REQUEST',
  DISPLAY: 'DISPLAY'
}


export const ORDERS_HISTORY_STATE = {
  INITIAL_FETCH: 'INITIAL_FETCH',
  ERROR: 'ERROR',
  DISPLAY: 'DISPLAY'
}